name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libxml-libxml-perl libxml-xslt-perl libxml-filter-xslt-perl mercurial help2man git openjdk-8-jre libncurses5-dev zlib1g-dev lib32z1-dev mesa-common-dev gcc-multilib g++-multilib cmake dos2unix tcl autoconf gperf bison flex gawk libtool libsdl-dev libsdl-image1.2 libsdl-ttf2.0-0 texinfo ninja-build qt5-qmake qttools5-dev-tools qt5-default libqt5svg5-dev qt5-image-formats-plugins qtbase5-dev qtdeclarative5-dev python3-tk
    - run: autoconf && ./configure --prefix=$PWD && make install
    - run: echo "CT_APPIMAGE=y" >> .config
    - run: ./bin/lnp-forge build
    - uses: actions/upload-artifact@v2
      with:
        name: LinuxDwarfPack-${{ github.sha }}-x86_64.AppImage
        path: LinuxDwarfPack-*-x86_64.AppImage
