name: Build LinuxDwarfPack package

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-16.04
    env:
      PKG_NAME: LinuxDwarfPack-${{ github.sha }}
    steps:
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libxml-libxml-perl libxml-xslt-perl libxml-filter-xslt-perl mercurial help2man git openjdk-8-jre libncurses5-dev zlib1g-dev lib32z1-dev mesa-common-dev gcc-multilib g++-multilib cmake dos2unix tcl autoconf gperf bison flex gawk libtool libsdl-dev libsdl-image1.2 libsdl-ttf2.0-0 texinfo ninja-build qt5-qmake qttools5-dev-tools qt5-default libqt5svg5-dev qt5-image-formats-plugins qtbase5-dev qtdeclarative5-dev python3-tk

    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        autoconf && ./configure --prefix=$PWD && make install
        echo "CT_LOG_PROGRESS_BAR=n" >> .config
        ./bin/lnp-forge build
    - name: Upload build log
      uses: actions/upload-artifact@v2
      with:
        name: build.log
        path: build.log
      if: ${{ failure() }}

    - name: Package
      run: |
        source .config && mv .build/src/lnp-${CT_LNP_VERSION} ${{ env.PKG_NAME }}
        tar cjf ${{ env.PKG_NAME }}.tbz2 ${{ env.PKG_NAME }}
    
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PKG_NAME }}.tbz2
        path: ${{ env.PKG_NAME }}.tbz2

    - name: Build AppImage
      run: |
        echo "CT_APPIMAGE=y" >> .config
        ./bin/lnp-forge clean build
    - name: Upload build log
      uses: actions/upload-artifact@v2
      with:
        name: build.log
        path: build.log
      if: ${{ failure() }}

    - name: Upload AppImage
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PKG_NAME }}.AppImage
        path: LinuxDwarfPack-*-x86_64.AppImage
